Fixed bug - music and scene pause when window is out of focus
HelloUnicorns/LD51 pull request #9
Opened 2022-10-02 17:07 UTC by idoweins

2022-10-02 17:50 UTC, mrnomm commented
Nice! But as you switch tabs the music and arrows get out of sync 😕.

2022-10-02 17:51 UTC, mrnomm requested changes
Nice! But as you switch tabs the music and arrows get out of sync 😕.

2022-10-03 09:49 UTC, idoweins commented
> Nice! But as you switch tabs the music and arrows get out of sync 😕.

Implemented workaround - game now enters pause mode and does not automatically continue afterwards

2022-10-03 11:05 UTC, mrnomm approved these changes

2022-10-03 11:06 UTC, merged